### PR TITLE
Issue: 27

### PR DESCRIPTION
**Pull request by mugdha273**
Issue: 27
Short description of what this resolves:
URL pattern for AnswerView
fixed typo of add_now to auto_now_add (pub_date as it is going to be constant always) in models.

### CODE REVIEW

**Comment by mugdha273** [comment]
accidentally closed PR#28, updated the PR to resolve merge conflicts
@TheRealSibasishBehera please take a look

**Comment by TheRealSibasishBehera** [comment]
Thats cool 


> accidentally closed PR#28, updated the PR to resolve merge conflicts @TheRealSibasishBehera please take a look

thats cool but
PR template is not followed , can you fix that please

**Comment by mugdha273** [comment]
> Thats cool
> 
> > accidentally closed PR#28, updated the PR to resolve merge conflicts @TheRealSibasishBehera please take a look
> 
> thats cool but PR template is not followed , can you fix that please

yea I edited that 🤝🏽

**Comment by TheRealSibasishBehera** [comment]
send a new pr please , just to be sure

**Comment by mugdha273** [comment]
sure

**Pull request closed without merging**
