### PR TITLE
Issue: 33

### PR DESCRIPTION
**Pull request by mugdha273**
Issue: 27
Short description of what this resolves:
allows get via list, put and patch via update, delete via destroy. 
serializer change->  include the author field in create, put, and patch requests, we need to define it in the QuestionSerializer and set the read_only attribute to False else runs into error.

### CODE REVIEW

**Review by TheRealSibasishBehera — CHANGES_REQUESTED** [review]
use `@api_view(['GET', 'PUT', 'PATCH', 'DELETE'])` decorator and use if else ladder 
basically it would be one view and url  but which brach to run would depend on method

**Comment by mugdha273** [comment]
> use `@api_view(['GET', 'PUT', 'PATCH', 'DELETE'])` decorator and use if else ladder 
> basically it would be one view and url  but which brach to run would depend on method

You mean function based view? 🥲🥲
Do we really need this decorators in modelviewset?

**Comment by TheRealSibasishBehera** [comment]
yeah i was thinking about function based views for these methods as they are easy to read and work with
but we can stick to class based 
let me test these and update you back

**Comment by mugdha273** [comment]
Perfect 🎉
I tested that on my end as well.

**Review by TheRealSibasishBehera — APPROVED** [review]

**Comment by TheRealSibasishBehera** [comment]
LGTM  ! Thanks

**Pull request merged**
