### PR TITLE
fix for issue #37 : unique constraint added

### PR DESCRIPTION
**Pull request by MistyRavager**
Issue: 37
Short description of what this resolves:
- checks for uniqueness of the pair (author,answers)

### CODE REVIEW

**Review by TheRealSibasishBehera — CHANGES_REQUESTED** [review]
there is `unique_together` field under Meta , please use that , its more readable

**Comment by MistyRavager** [comment]
the `unique_together` was shown as possible deprecation in django project documentation, thats why I chose not to use it. If you still want it, i can change it...
image

**Comment by MistyRavager** [comment]
updated fix, please check

**Review by TheRealSibasishBehera — APPROVED** [review]

**Comment by TheRealSibasishBehera** [comment]
> the `unique_together` field under Meta was shown as possible deprecation in django project documentation, thats why I chose not to use it. If you still want it, i can change it... image

Thank you .  Didnt know about that , will fix it

**Pull request merged**
