### PR TITLE
Create QuestionModel.py

### PR DESCRIPTION
**Pull request by vedant-z**
Issue: 3

Short description of what this resolves:
Created Question Model

Changes proposed in this pull request and/or Screenshots of changes:
Question model created

### CODE REVIEW

**Comment by vedant-z** [comment]
@TheRealSibasishBehera Review this one please.

**Review by TheRealSibasishBehera — CHANGES_REQUESTED** [review]
1. remove the foreign key , its in answer fields
2.change question_text to title , asked_by to author
3.add descripiton ,  no of upvotes , no of anwers
3 add a _str__ returning a string containing id and title
4. add add_now  =  true atrribute
5. add a updated_date

**Comment by vedant-z** [comment]
@TheRealSibasishBehera 

from django.db import models

class Question(models.Model):
    # Fields for the question text and the date/time it was asked
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    updated_date = models.DateTimeField('date updated', auto_now=True)

    # Additional fields for storing additional information about the question
    # such as the user who asked it and any tags or categories it belongs to
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    description = models.TextField()
    upvotes = models.PositiveIntegerField(default=0)
    answers = models.PositiveIntegerField(default=0)
    add_now = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.id}: {self.title}'


This are the required changes you suggested. I wanna clear that do i need to remove foreign key from Author and Ctegory as well?

**Comment by TheRealSibasishBehera** [comment]
i think you misunderstood . please add the add_now atrtribute to `pub_date` not a new field itself.
we want the date to be the time at which this model is created

**Comment by vedant-z** [comment]
@TheRealSibasishBehera Is this okay now?

**Comment by TheRealSibasishBehera** [comment]
LGTM
but your PR is not following the PR Template .
Can you fix that please

**Comment by vedant-z** [comment]
@TheRealSibasishBehera Done bro

**Pull request merged**
