### PR TITLE
Issue: 17

### PR DESCRIPTION
**Pull request by mugdha273**
Issue: 17

Short description of what this resolves:
Adds Question Serialzer

code block example of a serialized object using this serialiser
image

### CODE REVIEW

**Comment by TheRealSibasishBehera** [comment]
can you rewrite the author to return the username instead of the unique id in the serialised data.
eg in your example case it return `"author":2 ` , it should be say `"author":"xyz"`

**Comment by mugdha273** [comment]
> can you rewrite the author to return the username instead of the unique id in the serialised data. eg in your example case it return `"author":2 ` , it should be say `"author":"xyz"`

Sure, On it.

**Comment by mugdha273** [comment]
revised data:

>>> s= QuestionSerialzers(questions)
>>> print(s.data)
{'id': 1, 'author': 'user1', 'title': 'ques1', 'pub_date': '2022-12-20T17:33:22.918744Z', 'updated_date': '2022-12-20T17:33:22.918744Z', 'description': 'desc1', 'upvotes': 5, 'answers': 2}

**Comment by TheRealSibasishBehera** [comment]
LGTM 
Thanks @mugdha273

**Pull request merged**
